### ISSUE TITLE
Make failed in ubuntu 15.10

### ISSUE THREAD

**Issue by kuradakis** [idose/MT7610U#1]
Hi

I couldn't compile

This is the output:
root@alex-Latitude-E6540:~/MT7610U# make
make -C tools
make[1]: Entering directory '/root/MT7610U/tools'
gcc -g -Wall    bin2h.c   -o bin2h
make[1]: Leaving directory '/root/MT7610U/tools'
cp -f os/linux/Makefile.6 /root/MT7610U/os/linux/Makefile
make -C /lib/modules/4.2.0-35-generic/build SUBDIRS=/root/MT7610U/os/linux modules
make[1]: Entering directory '/usr/src/linux-headers-4.2.0-35-generic'
  CC [M]  /root/MT7610U/os/linux/../../os/linux/rt_profile.o
/root/MT7610U/os/linux/../../os/linux/rt_profile.c: In function ‘announce_802_3_packet’:
/root/MT7610U/os/linux/../../os/linux/rt_profile.c:334:16: warning: unused variable ‘pAd’ [-Wunused-variable]
  RTMP_ADAPTER *pAd = (RTMP_ADAPTER *)pAdSrc;
                ^
In file included from /root/MT7610U/include/rtmp_os.h:44:0,
                 from /root/MT7610U/include/rtmp_comm.h:75,
                 from /root/MT7610U/include/rt_config.h:33,
                 from /root/MT7610U/os/linux/../../os/linux/rt_profile.c:28:
/root/MT7610U/os/linux/../../os/linux/rt_profile.c: In function ‘STA_MonPktSend’:
/root/MT7610U/os/linux/../../os/linux/rt_profile.c:443:35: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
         DBGPRINT(RT_DEBUG_ERROR, ("%s : Size is too large! (%d)\n", __FUNCTION__, pRxBlk->DataSize + sizeof(wlan_ng_prism2_header)));
                                   ^
/root/MT7610U/include/os/rt_linux.h:660:16: note: in definition of macro ‘DBGPRINT_RAW’
         printk Fmt;               \
                ^
/root/MT7610U/os/linux/../../os/linux/rt_profile.c:443:9: note: in expansion of macro ‘DBGPRINT’
         DBGPRINT(RT_DEBUG_ERROR, ("%s : Size is too large! (%d)\n", __FUNCTION__, pRxBlk->DataSize + sizeof(wlan_ng_prism2_header)));
         ^
  CC [M]  /root/MT7610U/os/linux/../../sta/assoc.o
  CC [M]  /root/MT7610U/os/linux/../../sta/auth.o
  CC [M]  /root/MT7610U/os/linux/../../sta/auth_rsp.o
  CC [M]  /root/MT7610U/os/linux/../../sta/sync.o
  CC [M]  /root/MT7610U/os/linux/../../sta/sanity.o
  CC [M]  /root/MT7610U/os/linux/../../sta/rtmp_data.o
  CC [M]  /root/MT7610U/os/linux/../../sta/connect.o
  CC [M]  /root/MT7610U/os/linux/../../sta/wpa.o
  CC [M]  /root/MT7610U/os/linux/../../sta/sta_cfg.o
/root/MT7610U/os/linux/../../sta/sta_cfg.c: In function ‘RTMPIoctlShow’:
/root/MT7610U/os/linux/../../sta/sta_cfg.c:5401:85: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
             snprintf(extra, size, "Driver version-%s, %s %s\n", STA_DRIVER_VERSION, __DATE__, __TIME__ );
                                                                                     ^
/root/MT7610U/os/linux/../../sta/sta_cfg.c:5401:95: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
             snprintf(extra, size, "Driver version-%s, %s %s\n", STA_DRIVER_VERSION, __DATE__, __TIME__ );
                                                                                               ^
cc1: some warnings being treated as errors
scripts/Makefile.build:258: recipe for target '/root/MT7610U/os/linux/../../sta/sta_cfg.o' failed
make[2]: *** [/root/MT7610U/os/linux/../../sta/sta_cfg.o] Error 1
Makefile:1398: recipe for target '_module_/root/MT7610U/os/linux' failed
make[1]: *** [_module_/root/MT7610U/os/linux] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.2.0-35-generic'
Makefile:369: recipe for target 'LINUX' failed
make: *** [LINUX] Error 2
root@alex-Latitude-E6540:~/MT7610U# uname -r
4.2.0-35-generic
root@alex-Latitude-E6540:~/MT7610U# cat /etc/issue
Ubuntu 15.10 \n \l

root@alex-Latitude-E6540:~/MT7610U# cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.2.1-22ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)
Thank you

**Comment by idose** [comment]
I downloaded it from Mediatek's website.
I didn't finish it. :warning: 

This is Ralink's chip. Now is Mediatek's.
You can download it from vendors's website. 
Asus : http://www.asus.com/us/Networking/USBAC51/HelpDesk_Download/
Mediatek: http://www.mediatek.com/en/downloads1/downloads/

Or checkout to version 3950d4fa58d24bf3d33b92704016e0b77721738c.
